CREATE TABLE IF NOT EXISTS "Make"(
	"Id" UUID,
	"Name" VARCHAR(100) NOT NULL,
	"IsActive" BOOL NOT NULL,
	"DateCreated" TIMESTAMPTZ NOT NULL,
	"DateUpdated" TIMESTAMPTZ NOT NULL,
	CONSTRAINT "PK_Make" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Vehicle"(
	"Id" UUID,
	"MakeId" UUID,
	"Model" VARCHAR(100),
	"Color" VARCHAR(40) NOT NULL,
	"Year" TIMESTAMPTZ,
	"ForSale" BOOLEAN NOT NULL,
	"IsActive" BOOL NOT NULL,
	"DateCreated" TIMESTAMPTZ NOT NULL,
	"DateUpdated" TIMESTAMPTZ NOT NULL,
	CONSTRAINT "PK_Vehicle" PRIMARY KEY ("Id"),
	CONSTRAINT "FK_Vehicle_Make_MakeId" FOREIGN KEY ("MakeId") REFERENCES "Make"("Id")
);